title: NEWKozlukov
email: newkozlukov@gmail.com
description: |
    Noch ein weiterer [Serge] Kozlukov.<br/>
    A place for notes on learning math,
    naive opinions and inappropriate proclamations.
social_links:
  -
    url: https://twitter.com/newkozlukov
    ico: /assets/social-twitter.svg
  -
    url: https://github.com/newkozlukov
    ico: /assets/social-github.svg

# Urls
base_url: ""
url: "https://newkozlukov.github.io"
permalink: pretty

remote_theme: newkozlukov/jekyll-theme-newtype
plugins:
  - jekyll-feed
  - jekyll-remote-theme
show_drafts: true
